name: AWS OIDC example

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT...

jobs:
  deploy:
    name: Assume AWS role
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role-oidc
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Verification step 
        run: |
          aws s3 ls
